# Generated by Django 5.2.1 on 2026-02-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApi', '0002_alter_registration_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='public_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
